version: "3.8"

services:
  main-service:
    build: main_service
    image: "main"
    container_name: main
    ports:
      - 3000:3000
    networks:
      - backend
      - gateway
    env_file:
      - main_service.env
    environment:
      - PORT=3000
      - MONGO_CONNECTION=mongodb://mongo:27017/softarchdb
      - INFLUX_HOST=influxdb
    depends_on:
      - mongo
      - influxdb
    restart: "unless-stopped"
  redirect-microservice:
    build: redirect_microservice
    image: "redirect"
    container_name: redirect
    ports:
      - 3001:3001
    networks:
      - backend
      - gateway
    environment:
      - PORT=3001
      - REDIS_URL=redis://redis
      - INFLUX_HOST=influxdb
      - MAIN_SERVICE=http://main-service:3000
    depends_on:
      - influxdb
      - main-service
      - redis
    restart: "unless-stopped"
  mongo:
    image: "mongo:4.4.1-bionic"
    container_name: mongo
    networks:
      - backend
    volumes:
      - ./mongodb_data:/data/db
    restart: "unless-stopped"
  influxdb:
    image: "influxdb:1.7.10"
    container_name: influxdb
    networks:
      - backend
    volumes:
      - ./influxdb_data:/var/lib/influxdb
    restart: "unless-stopped"
  redis:
    image: "redis"
    container_name: redis
    networks:
      - backend
    restart: "unless-stopped"
  frontend-builder:
    build: frontend
    image: "frontend-builder"
    container_name: frontend-builder
    volumes:
      - ./frontend-static:/frontend-static
  nginx:
    build: nginx
    image: "nginx"
    container_name: nginx
    volumes:
      - ./frontend-static:/frontend-static
    ports:
      - 8000:8000
    networks: 
      - gateway
    depends_on:
      - redirect-microservice
      - main-service
      - frontend-builder
    restart: "unless-stopped"
networks:
    gateway:
        driver: bridge
    backend:
        driver: bridge
